[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.3",
    "django-ckeditor>=6.7.3",
    "pillow>=11.2.1",
]
