# Generated by Django 5.2.3 on 2025-06-10 23:18

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of your blog post', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated)', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Brief description shown on blog listing page', max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full blog post content with rich text editor')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_published', models.BooleanField(default=True, help_text='Make this post visible to visitors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this post should be published')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the project')),
                ('detailed_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed project description (optional)')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or image', null=True, upload_to='project_images/')),
                ('live_url', models.URLField(blank=True, help_text='Live demo URL (optional)')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL (optional)')),
                ('tech_stack', models.CharField(help_text='Technologies used (comma-separated)', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Display this project on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=100)),
                ('file', models.FileField(help_text='Upload your resume as PDF', upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text='Make this resume available for download')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Portfolio', max_length=100)),
                ('tagline', models.CharField(default='Software Developer & Creative Technologist', max_length=200)),
                ('bio_short', models.TextField(help_text='Brief bio for homepage hero section', max_length=500)),
                ('bio_long', ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed bio for about page')),
                ('profile_image', models.ImageField(blank=True, help_text='Professional headshot', null=True, upload_to='profile/')),
                ('email', models.EmailField(help_text='Professional email address', max_length=254)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('meta_description', models.TextField(blank=True, help_text='Site description for search engines', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
