# Generated by Django 5.2.3 on 2025-06-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Shivam Chaubey', max_length=100),
        ),
    ]
