# Generated by Django 5.2.3 on 2025-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_sitesettings_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='author_name',
            field=models.CharField(default='Shivam Chaubey', help_text='Author name for blog posts', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Hi, I am Shivam', help_text='Main hero section title', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_title',
            field=models.CharField(default='Shivam', help_text='Text for navbar brand', max_length=50),
        ),
    ]
