# Generated by Django 5.2.3 on 2025-06-18 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitesettings_author_name_sitesettings_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Project screenshot or image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=cloudinary.models.CloudinaryField(help_text='Upload your resume as PDF', max_length=255, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Professional headshot', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
